baseURL = "https://larua-hugo.canitia.nl/"
languageCode = "en-us"
title = "Larua voor Hugo"
theme = "larua-hugo"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"

