name = "Larua for Hugo"
license = "GPLv3"
licenselink = "https://github.com/boumannm/larua-hugo-theme/blob/master/LICENSE"
description = "A spinoff of Larua for Hugo."
homepage = "https://github.com/boumannm/larua-hugo-theme"
tags = [
  "blog",
  "minimal",
  "responsive",
  "simple",
  "clean",
  "personal"
]
min_version = "0.79"

[author]
  name = "Michael Boumann"
  homepage = "https://michaelboumann.com"