name = "Larua for Hugo"
license = "GPLv3"
licenselink = "https://github.com/pixelateddeveloper/larua-hugo/blob/master/LICENSE"
description = "A spinoff of Larua for Hugo."
homepage = "https://github.com/pixelateddeveloper/larua-hugo"
tags = [
  "blog",
  "minimal",
  "responsive",
  "simple",
  "clean",
  "personal"
]
min_version = "0.48"

[author]
  name = "PixelatedDeveloper"
  homepage = "https://pixelateddeveloper.com"