name = "Larua voor Hugo"
license = "GPLv3"
licenselink = "https://github.com/Canitia/larua-hugo/blob/master/LICENSE"
description = "Spinoff van Canitia's thema 'Larua' voor het Hugo platform"
homepage = "https://github.com/Canitia/larua-hugo"
tags = [
  "blog",
  "minimal",
  "responsive",
  "simple",
  "clean",
  "personal"
]
min_version = "0.48"

[author]
  name = "CanitiaThemes"
  homepage = "https://canitiathemes.com"